sudo: required

language: minimal

env:
  - IMAGE=registry.gitlab.com/bleemsync-dev/docker-autodevops-buildenvs/mmc-crosscompiler-docker-image:latest_internal

services:
  - docker

before_install:
  - docker login -u $GITLAB_USER -p $GITLAB_PASS registry.gitlab.com
  - docker pull ${IMAGE}
  - docker run ${IMAGE} bash -c "classic_make_nesc Makefile clean"
  - docker run ${IMAGE} bash -c "classic_make_nesc Makefile"
  - docker run ${IMAGE} bash -c "chown 600 ~/.keys/release_private_key.pem"
  - docker run ${IMAGE} bash -c "cd /var/www/html/cores/Automated_Builds/NESC\nput ${TARGETBUILD}.so" | sftp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.keys/release_private_key.pem docker@classicmodscloud.com"